version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - ford Documentation.md -o docs  # Run FORD to generate HTML into the docs/ directory
python:
  install:
    - requirements: requirements.txt