version: 2
sphinx:
  builder: dirhtml  # A fallback in case of any other static site files
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt  # Optional if you have extra requirements
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
jobs:
  pre_build:
    - pip install ford  # Install FORD if needed
  build:
    - ford Documentation.md  # This line runs FORD to regenerate the docs if needed

