version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
jobs:
  pre_build:
    - pip install ford  # Install FORD
  build:
    - ford Documentation.md -o docs  # Run FORD to generate HTML files into the docs/ directory