version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
python:
  install:
    - method: pip
      path: .
jobs:
  pre_build:
    - pip install ford  # Install FORD
  build:
    - ford Documentation.md -o docs  # Run FORD to generate documentation into the docs/ directory
sphinx:
  builder: dirhtml  # Allows serving of static HTML files
