version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9.6"
  commands:
    - pip install ford  # Explicitly install FORD
    - ford Documentation.md -o docs --debug # Run FORD to generate documentation into the docs/ directory