version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  commands:
    - pip install -r requirements.txt
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - ford Documentation.md -o docs/_build/html --debug
